cart_app/urls.py
from django.urls import path
from . import views

app_name ='cart_app'

urlpatterns = [
    path('cartD/', views.cart_details, name='cart_details'),
    path('remove/<int:pid>/', views.delete_cart, name='remove_cart'),
    path('add/<int:pk>/', views.addtocart, name='addcart'),
]

product_app/urls.py
from django.shortcuts import render
from django.urls import path
from . import views

app_name = 'product_app'

urlpatterns = [
    path('<int:pk>/', views.details, name='detail')
]

search_app/urls.py
from django.urls import path
from . import views


app_name='search_app'
urlpatterns = [
    path('search/', views.search, name='search')
]

vehicle_app/urls.py
from django.urls import path
from . import views

app_name = 'vehicle_app'


urlpatterns = [
    path('', views.home, name='home'),
    path('log/', views.log, name='log'),
    path('reg/', views.reg, name='reg'),
    path('logout', views.logout, name='logout'),
    path('<slug:c_slug>/', views.home, name='product_by_category'),
]

vehicles/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vehicle_app.urls')),
    path('prodCat/', include('product_app.urls')),
    path('cart/', include('cart_app.urls')),
    path('search/', include('search_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart_app/models.py
from django.contrib.auth.models import User
from django.db import models
from vehicle_app.models import AllVehicles


# Create your models here.
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(AllVehicles, on_delete=models.CASCADE)
    order_date = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ['item']
        verbose_name = 'Cart'
        verbose_name_plural ='Carts'

    def __str__(self):
        return '{}'.format(self.item)

product_app/models.py
from django.db import models

# Create your models here.

search_app/models.py
from django.db import models

# Create your models here.

vehicle_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User
from django.urls import reverse


# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    bio = models.TextField()
    image = models.ImageField(upload_to='userprofile')


    def __str__(self):
        return '{}'.format(self.user.username)


class AllVehicles(models.Model):
    v_types = [('Motor cycle', 'Motor cycle'), ('Car', 'Car'), ('Truck', 'Truck'), ('bycycle', 'bycycle'),
               ('auto rickshaw', 'auto rickshaw'), ]
    t_types = [('el', 'electrical'), ('pl', 'petrol'), ('dl', 'diesel'), ]
    vehicletype = models.CharField(max_length=150, blank=False, choices=v_types)
    t_type = models.CharField(max_length=150, blank=False, choices=t_types)
    v_name = models.CharField(max_length=200, blank=False)
    slug = models.SlugField(max_length=200, blank=False)
    v_img = models.ImageField(upload_to='vehicle', blank=True)
    desc = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    published = models.DateField(auto_now_add=True)
    available = models.BooleanField(default=True)

    class Meta:
        ordering = ('v_name',)
        verbose_name = 'Vehicle'
        verbose_name_plural = 'Vehicles'

    def get_url(self): # for dropdown selection
        return reverse('vehicle_app:product_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.v_name)

cart_app/views.py
from django.shortcuts import render, redirect
from .models import Cart
from vehicle_app.models import AllVehicles


# Create your views here.

def addtocart(request, pk):
    product = AllVehicles.objects.all().get(id=pk)
    print(product.price)
    if request.user.is_authenticated:
        try:
            items = Cart.objects.create(user=request.user, item=product)
            items.save()
        except:
            print('uuuuuuuuuu')
            # items = Cart.objects.create(user=request.user, item=product)
            # items.save()

    return redirect('cart_app:cart_details')


def cart_details(request, total=0, ):
    if request.user.is_authenticated:
        user = request.user
        cart_items = Cart.objects.all().filter(user=user)
        total_items = len(cart_items)
        for cart in cart_items:
            total += cart.item.price

    return render(request, 'cart.html', {'item': cart_items, 'total': total, 'items': total_items})


def delete_cart(request, pid):
    if request.user.is_authenticated:
        cart_item = Cart.objects.all().filter(id=pid)
        print(cart_item)
        cart_item.delete()

    return redirect('cart_app:cart_details')

product_app/views.py
from django.shortcuts import render
from vehicle_app.models import AllVehicles
# Create your views here.

def details(request,pk):
    try:
        vehicle = AllVehicles.objects.get(pk=pk)
        print(vehicle)
    except Exception as e:
        raise e
    return render(request,'details.html', {'vehicle':vehicle})

search_app/views.py
from django.db.models import Q
from django.shortcuts import render
from vehicle_app.models import AllVehicles

# Create your views here.

def search(request):
    product = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        product = AllVehicles.objects.all().filter(Q(v_name__contains=query) | Q(desc__contains=query))
    return render(request, 'search.html',{'query':query, 'products':product} )

vehicle_app/views.py
from django.contrib import auth
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from .models import AllVehicles, UserProfile


# Create your views here.


def home(request, c_slug=None):
    c_page = None
    product_list = None
    if c_slug is not None:
        print('dffddfdfdfdfdf')
        print(c_slug)
        #c_page = get_object_or_404(AllVehicles, slug=c_slug)
        product_list = AllVehicles.objects.all().filter(slug=c_slug, available=True)
    else:
        print('dffddfdfdfdfdf')
        print(c_slug)
        product_list = AllVehicles.objects.all().filter(available=True)
    #paginator = Paginator(product_list, 6)
    # try:
    #     page = int(request.GET.get('page', '1'))
    # except:
    #     page = 1
    # try:
    #     products = paginator.page(page)
    # except (EmptyPage, InvalidPage):
    #     products = Paginator.page(paginator.num_pages)

    return render(request, 'home.html', {'vehicle': product_list, 'category':c_page})


def log(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('psw')

        print(email)
        print(password)

        user = authenticate(username=email, password=password)
        if user is not None:
            auth.login(request, user)
            print(user)
            return redirect('/',)
        else:
            return redirect('/')

    return render(request, 'log.html', )

def logout(request):
    auth.logout(request)
    return redirect('/')

def reg(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        password = request.POST.get('psw')
        c_Pass = request.POST.get('cpsw')

        if email != '':
            if password == c_Pass:
                if User.objects.all().filter(email=email).exists():
                    print('User is Exists')
                    return redirect('vehicle_app:reg')
                else:
                    user = User.objects.create_user(username=name, email=email, password=password)
                    user.save()
                    return redirect('/')
            else:
                print('password incorrect')
                return redirect('vehicle_app:reg')
        else:
            print('fields empty')
            return redirect('vehicle_app:reg')
    return render(request, 'register.html', )

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% include 'navbar.html' %}
<div class="container" style="">
    {% block content %}
    {% endblock %}
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/cart.html
{% extends 'base.html' %}

{% block metadescription %}
cart
{% endblock %}

{% block title %}
cart
{% endblock %}

{% block content %}
<div class="row " style="margin-top:100px;">
  <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <table class="table my_custom_table">
      <thead class="my_custom_thead">
        <tr>
          <th colspan="5">Your items</th>
        </tr>
      </thead>
      <tbody>
      {% for it in item %}
      <tr>
        <td>
          <a href=""><img src="{{it.item.v_img.url}}" alt="" class="float-left rounded custom_image" style="width:120px; height:100px;"></a>
        </td>
        <td class="text-left">{{it.item.v_name}}<br>
          Price:{{it.item.price}}rs<br>
        </td>
        <td>
        <td>
          &nbsp;
<!--          <a href="" class="custom_a"><i href="" class="fa fa-minus custom_a"></i></a>-->
          &nbsp;
          <a href="{% url 'cart_app:remove_cart' it.id %}" class="custom_a"><i href="custom_icon" class="fa fa-trash custom_icon"></i></a>

        </td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
      <table class="table my_custom_table">
        <thead class="my_custom_thead">
          <tr>
            <th>
              Checkout
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              PLease review your shopping cart items before proceeding with the order payment.
            </td>
          </tr>
        <tr>
          <td class="text-left">
              Your total is : <strong>{{total}}</strong>
          </td>
        </tr>
        </tbody>
      </table>
    <div class="ma-auto">
      <a href="/" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
      &nbsp;<a href="" class="btn btn-success btn-block my_custom_button">Payment</a>
    </div>
  </div>
</div>

{% endblock %}

templates/details.html
{% extends 'base.html' %}

{% block metadescription %}
details
{% endblock %}

{% block title %}
{{vehicle.v_name}} details
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div>
        <div class="card border-primary"  style="margin-top:100px; width:700px;">
            <div class="card-body ">
                <form method="post">
                    {% csrf_token %}
                <h1 class="text-primary">{{vehicle.v_name}}</h1>
                <p>{{vehicle.desc}}</p>
                <img src="{{vehicle.v_img.url}}" width="500px" height="200px">
                <p>Price : {{vehicle.price}}</p>
                {% if vehicle.available is True %}
                <p>Available : Yes</p>
                {% else %}
                <p>Available : No</p>
                {% endif %}
                <a type="submit" href="{% url 'cart_app:addcart' vehicle.id %}" class="btn btn-primary">Add to cart</a>


                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/footer.html
{% load static %}
<footer class="bg-primary text-center text-lg-start">
    <div class="text-center my-footer">
        <p>&copy;buy_me pvt lmt</p>
    </div>
</footer>

templates/header.html
{% load static %}
<header class="logo">
    <a href="/"><img src="{% static 'img/buy_me_logo.png' %}" width="180px" ></a>
</header>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
buy_me
{% endblock %}

{% block title %}
buy_me
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3">
            <div class="card border-primary mb-3 mt-6" style="max-width: 18rem; margin-top:150px;">
              <div class="card-header">buy_me</div>
              <div class="card-body text-primary">
                <h5 class="card-title"></h5>
                <p class="card-text"><strong><i>buy_me</i></strong> is an online platform for selling and buying vehicles. Here we're providing all types of vehicles(electrical,petrol, diesel) and  used cars also. Use me well. </p>
              </div>
            </div>
        </div>
        <div class="col-6 ">
<!--            <img src="{% static 'img/buy_me_logo.png' %}">-->
            <div class="card border-primary mb-3 mt-6 scroll" style="max-width: 50rem; margin-top:100px;">
              <div class="card-body text-primary">
                  {% for vehi in vehicle %}
                  <form action="" method="post">
                      {% csrf_token %}
                  <div class="card my_table">
                      <div class="card-body ">
                          <table class="my_table">
                              <thead style="color:#000000; ">{{vehi.v_name}}</thead>
                              <tr >
                                <td><img src="{{vehi.v_img.url}}" width="300px" height="150px"></td>
                                  <td rowspan="1">
                                      Vehicle type : {{vehi}}<br>
                                      Tank type : {{vehi.get_t_type_display}}<br>
                                      Price : {{vehi.price}}rs<br>
                                      Date : {{vehi.published}}</td>
                                        {{vehi.id}}
                              </tr>

                          </table>
                          {% if user.is_authenticated %}
                            <a type="submit" href="{% url 'product_app:detail' vehi.id %}" class="btn btn-primary" style="margin-left:400px;">Details</a>
                          {% endif %}
                      </div>
                  </div>
                  </form>
                  {% endfor %}
              </div>
            </div>
        </div>
        <div class="col-3 log ">

            <div class="card border-primary mb-3 mb-3 mt-3" style="max-width: 18rem;">
              <div class="card-header">Login</div>
              <div class="card-body">
                {% if user.is_authenticated %}
                  <img src="{{user.userprofile.image.url}}" width="200px" class="rounded">
                <h5 class="card-title">{{user}}</h5>
                  <p>{{user.userprofile.bio}}</p>
                  <a href="/logout">logout</a>
                  {% else %}
                    <form method="post" action="{% url 'vehicle_app:log' %}" class="">
                        {% csrf_token %}
                      <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label"></label>
                        <input type="text" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                      </div>
                      <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">Password</label>
                        <input type="password" name="psw" class="form-control" id="exampleInputPassword1">
                      </div>
                            <button type="submit" class="btn btn-primary">Submit</button>&nbsp;&nbsp;
                            <a href="{% url 'vehicle_app:reg' %}" style="font-size:20px;">Register</a>
                    </form>
                  {% endif %}
              </div>
            </div>

        </div>
        </div>
{% endblock %}

templates/log.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
buy_me
{% endblock %}

{% block title %}
login
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col log">
        </div>
        <div class="col log">
<!--            <img src="{% static 'img/buy_me_logo.png' %}">-->
            <form method="post" class="log">
                {% csrf_token %}
              <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Email address</label>
                <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
              </div>
              <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Password</label>
                <input type="password" name="psw" class="form-control" id="exampleInputPassword1">
              </div>
                    <button type="submit" class="btn btn-primary">Submit</button>&nbsp;&nbsp;
                    <a href="{% url 'vehicle_app:reg' %}" style="font-size:20px;">Register</a>
                </form>
            </div>
        <div class="col log">
        </div>
    </div>


{% endblock %}

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top nav-text">
  <div class="container-fluid">
    <a class="navbar-brand" style="font-size:30px;" href="#"><strong>buy_me</strong></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item  dropdown {% if 'vehicle_app' in  request.path %}active{% endif %} ">
          <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            vehicles
          </a>
            <ul class="dropdown-menu drop" aria-labelledby="navbarDropdown">
          {% for v in link %}
              <li><a class="dropdown-item" href="{{v.get_url}}">{{v}}</a></li>
          {% endfor %}
            </ul>
        </li>
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart_app:cart_details' %}"><i class="fa fa-shopping-cart" aria-hidden="true"></i></a>        <li class="nav-item">
        </li>
      {% endif %}
        </li>
        <li class="nav-item active">

      <ul class="navbar-nav  mb-6 mb-lg-0">
      </ul>
        </li>
      </ul>
      <form class="d-flex" action="{% url 'search_app:search' %}" method="GET">
        {% csrf_token %}
        <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-success " name='' type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
buy_me
{% endblock %}

{% block title %}
register
{% endblock %}

{% block content %}

<div class="row" style="margin-top:100px;">
    <div class="col-6">
        <div class="card border-0 my_card"style="" >
        <form class="" method="POST">
            {% csrf_token %}
          <div class="form-group">
            <label for="exampleInputPassword1">Name</label>
            <input type="text" class="form-control" name="name" placeholder="Your name">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" class="form-control" name="email" aria-describedby="emailHelp" placeholder="Enter email">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" class="form-control" name="psw" placeholder="Password">
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Confirm Password</label>
            <input type="password" class="form-control" name="cpsw" placeholder="Confirm Password">
          </div>
          <div class="form-group form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Check me out</label>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    </div>

</div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}

{% block metadescription %}
seacrh
{% endblock %}

{% block title %}
search
{% endblock %}

{% block content %}
  <div  style="margin-top:100px;">
    <p class="text-center mt_search_text">You have searched for :<b>{{query}}</b></p>
  </div>
  <div class="container">
    <div class="row mx-auto">
        {% for product in products %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-4 col-lg-4">
                <div class="card text-center" style="min-width:18rem; ">
                    <a href="{{product.get_url}}"><img class="card-img-top my_image he" src="{{product.v_img.url}}" alt="{{product.name}}" height="150px"></a>
                    <div class="card-body">
                        <h4>{{product.v_name}}</h4>
                        <p>{{product.desc}}</p>
                        <p>Price        : {{product.price}}</p>
                        <p>Vehicle type : {{product.vehicletype}}&nbsp;{{product.get_t_type_display}}</p>
                        {% if user.is_authenticated %}
                        <a class="btn btn-primary" href="{% url 'cart_app:addcart' product.id %}">Add to cart</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% empty %}
      <div class="row mx-auto">
        <p class="text-center my_search_text">0 result found</p>
      </div>
      {% endfor %}
    </div>
    </div>

{% endblock %}